platform :ios, '17.0'
use_frameworks!

target 'GemWalletExample' do
  # Use the local GemWallet pod for testing
  pod 'GemWallet', :path => '../'
  
  # Required dependencies
  pod 'GRDB.swift', '~> 7.0'
  pod 'GRDBQuery', '~> 0.10'
  pod 'BigInt', '~> 5.2'
  pod 'Starscream', '~> 4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      config.build_settings['SWIFT_VERSION'] = '6.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end

